### Feature Product — CREATE (SIN AUTH)
@baseUrl = http://localhost:4000

### CREATE -> 201
POST {{baseUrl}}/api/productos
Content-Type: application/json

{
  "sku": "BEB-0001",
  "nombre": "Latte",
  "descripcion": "Café con leche vaporizada",
  "precio": 8500
}

### CREATE con sku repetido -> 409
POST {{baseUrl}}/api/productos
Content-Type: application/json

{
  "sku": "BEB-0001",
  "nombre": "Otro producto",
  "precio": 5000
}
